### ISSUE TITLE
dc in trsro

### ISSUE THREAD

**Issue by jrgal74** [SDClowen/RSBot#578]
keeps getting dc from the guard in trsro

**Comment by SDClowen** [comment]
fixed.

**Comment by jrgal74** [comment]
iam still facing the same problem , even after i reinstall 

also when i open the game i get (not in game) in the bot 
and i get this message in the log
"
Could not copy old profile data to the new profile: Could not find a part of the path 'C:\Users\inter\AppData\Roaming\RSBot\User\inter\autologin.data'.

<Warning> 	Client process exited!

"

**Comment by jrgal74** [comment]
iam still facing the same problem , even after i reinstall

also when i open the game i get (not in game) in the bot
and i get this message in the log
"
Could not copy old profile data to the new profile: Could not find a part of the path 'C:\Users\inter\AppData\Roaming\RSBot\User\inter\autologin.data'.

Client process exited!

"
